version: '3.4'

services:
  tst_asp_auth_mysql:
    image: ${DOCKER_REGISTRY-}tstaspauthmysql
    build:
      context: .
      dockerfile: TST_ASP_Auth_MySql/Dockerfile
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pwd'      
      MYSQL_ROOT_PASSWORD: 'pwd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'